---
doc:
  - |
    **[CCE]** Fixed kubeconfig in ``datasource/opentelekomcloud_cce_cluster_kubeconfig_v3`` (`#2785 <https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/2785>`_)
